### ISSUE TITLE
Is there an easy way to add endpoint ?

### ISSUE THREAD

**Issue by donnib** [rrostt/hassio-backup-s3#1]
Hi,
I want to use this addon with Minio so i need a way to set the endpoint and point to the URL/ip address. Is there a way to do that in a easy way ?

/donnib

**Comment by rrostt** [comment]
No,

you'd have to change Dockerfile to install any necessary software for Minio, and then update run.sh (given you still reference run.sh in the new Dockerfile).

Let me know if you do this, and I can link your repo in readme.

Cheers
